### ISSUE TITLE
MissingPluginException on iOS simulator

### ISSUE THREAD

**Issue by a-v-ebrahimi** [rmtmckenzie/flutter_native_device_orientation#39]
When I call this : 
`nativeOrientation = (await NativeDeviceOrientationCommunicator().orientation(useSensor: true)).index;`

I receive this :
```
Unhandled Exception: MissingPluginException(No implementation found for method getOrientation on channel com.github.rmtmckenzie/flutter_native_device_orientation/orientation)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:175:7)
<asynchronous suspension>
#1      NativeDeviceOrientationCommunicator.orientation (package:native_device_orientation/native_device_orientation.dart:42:25)
<asynchronous suspension>
```

**Comment by rmtmckenzie** [comment]
Not entirely sure what's going on here. It should work fine. If it's still happening in newest version please re-open.
