### ISSUE TITLE
"Attempt to invoke virtual method" occurs on NativeDeviceOrientationCommunicator.resume

### ISSUE THREAD

**Issue by Hwan-seok** [rmtmckenzie/flutter_native_device_orientation#49]
When I call `NativeDeviceOrientationCommunicator().resume()`, the following error occurs.

I tested on 
Platform: Android 12
Plugin version: 1.1.4

```
PlatformException (PlatformException(error, Attempt to invoke virtual method 'java.lang.String com.github.rmtmckenzie.native_device_orientation.NativeOrientation.name()' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.github.rmtmckenzie.native_device_orientation.NativeOrientation.name()' on a null object reference
	at com.github.rmtmckenzie.native_device_orientation.NativeDeviceOrientationPlugin$StreamHandler$1.receive(NativeDeviceOrientationPlugin.java:115)
	at com.github.rmtmckenzie.native_device_orientation.SensorOrientationListener.startOrientationListener(SensorOrientationListener.java:45)
	at com.github.rmtmckenzie.native_device_orientation.NativeDeviceOrientationPlugin$MethodCallHandler.onMethodCall(NativeDeviceOrientationPlugin.java:86)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:319)
	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
))
```

**Comment by akihisasengoku** [comment]
Our product also encountered the same error.

- Platform: Android 8.0 - 13.0
- Plugin version: 1.1.4

```
PlatformException: PlatformException(error, Attempt to invoke virtual method 'java.lang.String java.lang.Enum.name()' on a null object reference, null, )
  File "native_device_orientation.dart", line 55, in NativeDeviceOrientationCommunicator.resume
  File "orientation_controller.dart", line 79, in _OrientationControllerImpl.resume
```

**Comment by ethancadoo** [comment]
Same here. Crashes immediately, found this same error message via Sentry.

**Comment by akihisasengoku** [comment]
I think the timing of calling `resume()` is the cause of the error.
The code that causes the problem is below from the error log.
https://github.com/rmtmckenzie/flutter_native_device_orientation/blob/be86db1b9e08f812bb76204d1c7525d5b5c5d6b8/android/src/main/java/com/github/rmtmckenzie/native_device_orientation/SensorOrientationListener.java#L45
`resume()` is expected to be called after `pause()`, but may be called otherwise depending on the application code implementation. 
I want to add null check for `lastOrientation`.

**Comment by vishalvishvakarma1111** [comment]
Same issue i am getting 

<img width="1554" alt="Screenshot 2023-11-27 at 4 03 40 PM" src="https://github.com/rmtmckenzie/flutter_native_device_orientation/assets/70423403/6c93869e-7251-47d3-8c09-4514245e5a64">

**Comment by rmtmckenzie** [comment]
Hmm, that's weird. @rpelant can you give the exact steps you've followed to reproduce that? And you're saying you're using the camera plugin and the user is returning to the app - do you mean that the camera is started, the app is closed, then on returning to the app that's when this error is seen?

**Comment by rmtmckenzie** [comment]
If at all possible it'd be great if you could create a project that is able to reproduce this, i.e. with the example app.

**Comment by rpelant** [comment]
Sorry not to answer sooner, I have upgraded to version 2.0.3 and the error is now the same but with different call stack (why the callstack looks so weird? debug symbols missing?). The error is collected from crashlytics in production,  on my development phone I am unable to reproduce. This error appears on different phone models and Android versions.


Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: PlatformException(error, Attempt to invoke virtual method 'java.lang.String java.lang.Enum.name()' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Enum.name()' on a null object reference
	at com.github.rmtmckenzie.native_device_orientation.d.l(Unknown Source:0)
	at com.github.rmtmckenzie.native_device_orientation.d.k(Unknown Source:0)
	at com.github.rmtmckenzie.native_device_orientation.b.a(Unknown Source:2)
	at com.github.rmtmckenzie.native_device_orientation.i.a(Unknown Source:8)
	at com.github.rmtmckenzie.native_device_orientation.d.a(Unknown Source:69)
	at x6.k$a.a(Unknown Source:17)
	at l6.c.l(Unknown Source:18)
	at l6.c.m(Unknown Source:40)
	at l6.c.i(Unknown Source:0)
	at l6.b.run(Unknown Source:12)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8893)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
)
       at StandardMethodCodec.decodeEnvelope(message_codecs.dart:651)
       at MethodChannel._invokeMethod(platform_channel.dart:322)
       at MethodChannelNativeDeviceOrientation.resume(native_device_orientation_method_channel.dart:60)

**Comment by rpelant** [comment]
I use Sensor orientation and tried to find out from where nulls can come in SensorOrientationListener.java

only place where orientation is null is in initializer, can that be initialized with NativeOrientation.Unknown ?
`  private NativeOrientation lastOrientation = null;
`
and there it is used
`@Override
  public void startOrientationListener() {
    if (orientationEventListener != null) {
      callback.receive(lastOrientation);
      return;
    }

    orientationEventListener = new OrientationEventListener(activity, rate.nativeValue) {
      @Override
      public void onOrientationChanged(int angle) {
        NativeOrientation newOrientation = calculateSensorOrientation(angle);

        if (!newOrientation.equals(lastOrientation)) {
          lastOrientation = newOrientation;
          callback.receive(newOrientation);
        }
      }
    };
    if (orientationEventListener.canDetectOrientation()) {
      orientationEventListener.enable();
    }
  }`

**Comment by shinriyo** [comment]
it happens in iOS also
is this plugin closed????

**Comment by noze12** [comment]
I can reproduce this with the simple app below.

```dart
import 'package:flutter/material.dart';
import 'package:native_device_orientation/native_device_orientation.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: NativeDeviceOrientationReader(
          useSensor: true,
          builder: (context) {
            final orientation = NativeDeviceOrientationReader.orientation(
              context,
            );
            return Center(child: Text('Hello, World! $orientation'));
          },
        ),
      ),
    );
  }
}
```

Steps to reproduce:
1. Keep the device still (do not change orientation after app start or restart).
2. Slightly swipe up from the bottom to open the app switcher.
3. Without switching apps, return to the same app.
→ The error occurs at this moment.

Android version: 16
Flutter version:  3.32.0
Plugin version: 2.0.3
